version: "3.1"
services:
  prlmntq_gateway:
    build: .
    image: prlmntq_gateway
    container_name: prlmntq_gateway
    restart: always
    ports:
      - 8001:5000
    volumes:
      - .:/usr/src/gateway
    networks:
      - prlmntq_net

networks:
  prlmntq_net:
    external: true
